# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from interface.vigenereInterface import Ui_Vigenere
from interface.extendedVigenereInterface import Ui_ExtendedVigenere
from interface.playfairInterface import Ui_Playfair
from interface.oneTimePadInterface import Ui_OneTimePad

class Ui_Homepage(object):
    def openVigenere(self) :
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Vigenere()
        self.ui.setupUi(self.window)
        self.window.show()
    
    def openExtendedVigenere(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_ExtendedVigenere()
        self.ui.setupUi(self.window)
        self.window.show()
    
    def openPlayfair(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Playfair()
        self.ui.setupUi(self.window)
        self.window.show()

    def openOneTimePad(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_OneTimePad()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, Homepage):
        Homepage.setObjectName("Classical Cryptography")
        Homepage.resize(1000, 650)
        Homepage.setStyleSheet("background: #E2CD93;")
        self.centralwidget = QtWidgets.QWidget(Homepage)
        self.centralwidget.setObjectName("centralwidget")
        
        self.VigenerePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.VigenerePushButton.setGeometry(QtCore.QRect(170, 210, 301, 101))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.VigenerePushButton.setFont(font)
        self.VigenerePushButton.setStyleSheet("background: #D19B47;\n"
        "border-radius: 30px;\n"
        "\n"
        "font-style: normal;\n"
        "font-weight: 700;\n"
        "font-size: 22px;\n"
        "line-height: 49px;\n"
        "text-align: center;\n"
        "\n"
        "color: #FFFFFF;")
        self.VigenerePushButton.setObjectName("VigenerePushButton")
        self.VigenerePushButton.clicked.connect(self.openVigenere)
        self.VigenerePushButton.clicked.connect(Homepage.close)
        
        self.ExtendedVigenerePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExtendedVigenerePushButton.setGeometry(QtCore.QRect(530, 210, 301, 101))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.ExtendedVigenerePushButton.setFont(font)
        self.ExtendedVigenerePushButton.setStyleSheet("background: #D19B47;\n"
        "border-radius: 30px;\n"
        "\n"
        "font-style: normal;\n"
        "font-weight: 700;\n"
        "font-size: 22px;\n"
        "line-height: 49px;\n"
        "text-align: center;\n"
        "\n"
        "color: #FFFFFF;")
        self.ExtendedVigenerePushButton.setObjectName("ExtendedVigenerePushButton")
        self.ExtendedVigenerePushButton.clicked.connect(self.openExtendedVigenere)
        self.ExtendedVigenerePushButton.clicked.connect(Homepage.close)

        self.PlayfairPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.PlayfairPushButton.setGeometry(QtCore.QRect(170, 380, 301, 101))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.PlayfairPushButton.setFont(font)
        self.PlayfairPushButton.setStyleSheet("background: #D19B47;\n"
        "border-radius: 30px;\n"
        "\n"
        "font-style: normal;\n"
        "font-weight: 700;\n"
        "font-size: 22px;\n"
        "line-height: 49px;\n"
        "text-align: center;\n"
        "\n"
        "color: #FFFFFF;")
        self.PlayfairPushButton.setObjectName("PlayfairPushButton")
        self.PlayfairPushButton.clicked.connect(self.openPlayfair)
        self.PlayfairPushButton.clicked.connect(Homepage.close)
        
        self.OTPPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.OTPPushButton.setGeometry(QtCore.QRect(530, 380, 301, 101))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.OTPPushButton.setFont(font)
        self.OTPPushButton.setStyleSheet("background: #D19B47;\n"
        "border-radius: 30px;\n"
        "\n"
        "font-style: normal;\n"
        "font-weight: 700;\n"
        "font-size: 22px;\n"
        "line-height: 49px;\n"
        "text-align: center;\n"
        "\n"
        "color: #FFFFFF;")
        self.OTPPushButton.setObjectName("OTPPushButton")
        self.OTPPushButton.clicked.connect(self.openOneTimePad)
        self.OTPPushButton.clicked.connect(Homepage.close)
        
        self.Judul = QtWidgets.QLabel(self.centralwidget)
        self.Judul.setGeometry(QtCore.QRect(170, 60, 681, 71))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(36)
        self.Judul.setFont(font)
        self.Judul.setStyleSheet("color: #B67F57;")
        self.Judul.setObjectName("Judul")
        
        self.createdby = QtWidgets.QLabel(self.centralwidget)
        self.createdby.setGeometry(QtCore.QRect(230, 570, 551, 71))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(12)
        self.createdby.setFont(font)
        self.createdby.setStyleSheet("color: #B67F57;")
        self.createdby.setObjectName("createdby")
        
        Homepage.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Homepage)
        self.statusbar.setObjectName("statusbar")
        Homepage.setStatusBar(self.statusbar)

        self.retranslateUi(Homepage)
        QtCore.QMetaObject.connectSlotsByName(Homepage)

    def retranslateUi(self, Homepage):
        _translate = QtCore.QCoreApplication.translate
        Homepage.setWindowTitle(_translate("Homepage", "Homepage"))
        self.VigenerePushButton.setText(_translate("Homepage", "Vigenere Cipher"))
        self.ExtendedVigenerePushButton.setText(_translate("Homepage", "Extended Vigenere"))
        self.PlayfairPushButton.setText(_translate("Homepage", "Playfair Cipher"))
        self.OTPPushButton.setText(_translate("Homepage", "One Time Pad (OTP)"))
        self.Judul.setText(_translate("Homepage", "Classical Cryptography"))
        self.createdby.setText(_translate("Homepage", "Created by : 18220005 Muhammad Rifqi Riansyah M & 18220049 Rachmad Hidayat"))
