# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 650)
        MainWindow.setStyleSheet("background: #E2CD93;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.VigenerePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.VigenerePushButton.setGeometry(QtCore.QRect(170, 210, 301, 101))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.VigenerePushButton.setFont(font)
        self.VigenerePushButton.setStyleSheet("background: #D19B47;\n"
"border-radius: 30px;\n"
"\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 22px;\n"
"line-height: 49px;\n"
"text-align: center;\n"
"\n"
"color: #FFFFFF;")
        self.VigenerePushButton.setObjectName("VigenerePushButton")
        self.ExtendedVigenerePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExtendedVigenerePushButton.setGeometry(QtCore.QRect(530, 210, 301, 101))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.ExtendedVigenerePushButton.setFont(font)
        self.ExtendedVigenerePushButton.setStyleSheet("background: #D19B47;\n"
"border-radius: 30px;\n"
"\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 22px;\n"
"line-height: 49px;\n"
"text-align: center;\n"
"\n"
"color: #FFFFFF;")
        self.ExtendedVigenerePushButton.setObjectName("ExtendedVigenerePushButton")
        self.PlayfairPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.PlayfairPushButton.setGeometry(QtCore.QRect(170, 380, 301, 101))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.PlayfairPushButton.setFont(font)
        self.PlayfairPushButton.setStyleSheet("background: #D19B47;\n"
"border-radius: 30px;\n"
"\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 22px;\n"
"line-height: 49px;\n"
"text-align: center;\n"
"\n"
"color: #FFFFFF;")
        self.PlayfairPushButton.setObjectName("PlayfairPushButton")
        self.OTPPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.OTPPushButton.setGeometry(QtCore.QRect(530, 380, 301, 101))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.OTPPushButton.setFont(font)
        self.OTPPushButton.setStyleSheet("background: #D19B47;\n"
"border-radius: 30px;\n"
"\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 22px;\n"
"line-height: 49px;\n"
"text-align: center;\n"
"\n"
"color: #FFFFFF;")
        self.OTPPushButton.setObjectName("OTPPushButton")
        self.Judul = QtWidgets.QLabel(self.centralwidget)
        self.Judul.setGeometry(QtCore.QRect(170, 60, 681, 71))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(36)
        self.Judul.setFont(font)
        self.Judul.setStyleSheet("color: #B67F57;")
        self.Judul.setObjectName("Judul")
        self.createdby = QtWidgets.QLabel(self.centralwidget)
        self.createdby.setGeometry(QtCore.QRect(230, 570, 551, 71))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(12)
        self.createdby.setFont(font)
        self.createdby.setStyleSheet("color: #B67F57;")
        self.createdby.setObjectName("createdby")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.VigenerePushButton.setText(_translate("MainWindow", "Vigenere Cipher"))
        self.ExtendedVigenerePushButton.setText(_translate("MainWindow", "Extended Vigenere"))
        self.PlayfairPushButton.setText(_translate("MainWindow", "Playfair Cipher"))
        self.OTPPushButton.setText(_translate("MainWindow", "One Time Pad (OTP)"))
        self.Judul.setText(_translate("MainWindow", "Classical Cryptography"))
        self.createdby.setText(_translate("MainWindow", "Created by : 18220005 Muhammad Rifqi Riansyah M & 18220049 Rachmad Hidayat"))
